---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: "./svm-latex-cv.tex"
geometry: margin=1in

title: "CV"
author: Pin Shuai

jobtitle: "Post Doctorate Research Associate"
address: "Pacific Northwest National Laboratory · 902 Battelle Blvd, Richland, WA 99354"
fontawesome: yes
email: pin.shuai@pnnl.gov
# github: svmiller
# twitter: stevenvmiller
phone: "509-372-6999"
web: pinshuaiphd.com
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Research Topics

Groundwater and surface water interactions, nutrient cycling, hyporheic zone, field hydrogeology, numerical modeling and techniques.

# Education

*Texas A&M University (College Station, TX)*, Ph.D. Geology \hfill 2017

Dissertation: [Nutrients and Contaminants Fate and Transport under the Impact of Groundwater and Surface Water Interactions](https://oaktrust.library.tamu.edu/handle/1969.1/165937)

Advisors: Dr. Peter Knappett and Dr. M. Bayani Cardenas (University of Texas, Austin)

*Wuhan University (China)*, M.S. Water Resources Engineering \hfill 2013

*Wuhan University (China)*, B.S. Water Resources Engineering \hfill 2011

# Research Experience

*Post Doctorate Research Associate, Advanced Study & Development Group* \hfill 2017 - present

Pacific Northwest National Laboratory, Richland, Washington

*Graduate Research Assistant, Department of Geology and Geophysics* \hfill 2013 - 2017

Texas A&M University, College Station, Texas

*Alternate Student Fellowship, Atmospheric Sciences & Global Change Group* \hfill summer, 2016

Pacific Northwest National Laboratory, Richland, Washington

*Graduate Research Assistant, College of Water Resources and Hydropower Engineering* \hfill 2011 - 2013

Wuhan University, Wuhan, China

# Publications

Also see my [Google Scholar](https://scholar.google.com/citations?user=Md_6je0AAAAJ&hl=en) and [ORCiD](https://orcid.org/0000-0003-2511-9828)

## Journal Articles

[8] Zachara J., X. Chen, X. Song, **P. Shuai**, C. Murray, C. Resch. (2020). Kilometer-scale hydrologic exchange flows in a river corridor and their implications to solute migration. *Water Resources Research*. https://doi.org/10.1029/2019WR025258

[7] **Shuai, P.**, X. Chen, X. Song, G. Hammond, J. Zachara, P. Royer, H. Ren, W. Perkins, M. Richmond, M. Huang (2019). Dam Operations and Subsurface Hydrogeology Control Dynamics of Hydrologic Exchange Flows in a Regulated River Reach. *Water Resources Research*. https://doi.org/10.1029/2018WR024193

[6] Berube, M., K. Jewell, K. Myers, P. S.K. Knappett, **P. Shuai**, N. Dimova, A. Hossain, M. Lipsi, S. Hossain, J. Peterson, K. M. Ahmed, S. Datta (2018). The fate of arsenic in groundwater discharged to the Meghna River, Bangladesh. *Environmental Chemistry*, 15(2), 29. https://doi.org/10.1071/EN17104

[5] **Shuai, P.**, M. B. Cardenas, P. S. K. Knappett, P. C. Bennett, B. T. Neilson (2017). Denitrification in the banks of fluctuating rivers: The effects of river stage amplitude, sediment hydraulic conductivity and dispersivity, and ambient groundwater flow. *Water Resources Research*, 53(9), 7951–7967. https://doi.org/10.1002/2017WR020610

[4] **Shuai, P.**, P. S. K. Knappett , S. Hossain, A. Hosain, K. Rhodes, K. M. Ahmed, M. B. Cardenas (2017). The Impact of the Degree of Aquifer Confinement and Anisotropy on Tidal Pulse Propagation. *Groundwater*, 55(4), 519–531. https://doi.org/10.1111/gwat.12509

[3] Knappett, P.S.K., B.J. Mailloux, I. Choudhury, M.R. Khan, H.A. Michael, S. Barua, D.R. Mondal, M.S. Steckler, S.H. Akhter, K.M. Ahmed, B. Bostick, C.F. Harvey, M. Shamsudduha, **P. Shuai**, I. Mihajlov, R. Mozumder, A. van Geen (2016). Vulnerability of low-arsenic aquifers to municipal pumping in Bangladesh. *Journal of Hydrology*, 539, 674–686. https://doi.org/10.1016/j.jhydrol.2016.05.035

[2] Briody, A.C., M.B. Cardenas, **P. Shuai**, P.S.K. Knappett, and P.C. Bennett (2016). Groundwater flow, nutrient, and stable isotope dynamics in the parafluvial-hyporheic zone of the regulated Lower Colorado River (Texas, USA) over the course of a small flood. *Hydrogeology Journal*. https://doi:10.1007/s10040-016-1365-3.

[1] **Shuai, P.**, L. Shi, S. Cai and J. Yang (2014). The usage of bromide as a tracer to estimate groundwater recharge rate at Northern China Plain. *Journal of Irrigation and Drainage*. 33, no. 2:11-16. (In Chinese) [[link]](http://www.cqvip.com/qk/93783a/201402/49526144.html)

## Conference Proceedings

[1] Knappett, P. S. K., K. Myers, **P. Shuai**, K. Rhodes, K. Jewell, J. Peterson, N. Dimova et al. (2016). Tracking the fate of arsenic in groundwater discharged to the Meghna River. *In Arsenic Research and Global Sustainability: Proceedings of the Sixth International Congress on Arsenic in the Environment (As2016)*, June 19-23, 2016, Stockholm, Sweden, p. 43. CRC Press. [[link]](https://www.crcpress.com/Arsenic-Research-and-Global-Sustainability-Proceedings-of-the-Sixth-International/Bhattacharya-Vahter-Jarsjo-Kumpiene-Ahmad-Sparrenbom-Jacks-Donselaar-Bundschuh-Naidu/p/book/9781138029415)

## Working Papers and Works in Progress

[3] **Shuai P.**, X. Chen, X. Song, K. Chen and G. Hammond. (2019). Hydrologic Exchange Flows Alter River Corridor Thermal Regime in a Regulated River.  (*Under review at Water Resources Research*)

<!-- [5] Zheng L., L. Wang, T. Wang, J. Zhou, **P. Shuai**; K. Singh, Z. Wang, and X. Chen. (2019). A pore-scale diagnosis of critical Reynolds number for shear-thinning flow in porous media. (*Under Review at Chemical Engineering Science*) -->

[2] Song X., X. Chen, J.M. Zachara, J. Gomez-Velez, **P. Shuai**, H. Ren, and G. Hammond. (2019). Dynamic River Stage Variations Lead to Multimodal Residence Time Distributions of Hydrological Exchange Flow. (*Under review at Water Resources Research*)

[1] Chen K., X. Chen, X. Song, G. Hammond, H. Zhan, **P. Shuai**, and J. M. Zachara. (2019). Using Ensemble Data Assimilation to Estimate Transient Hydrologic Exchange Fluxes under Highly Dynamic Flow Conditions. (*Under review at Water Resources Research*)



<!-- [1] Wang L., **P. Shuai**, P. S. K. Knappett, M. B. Cardenas. Accumulation of arsenic in dynamic iron oxide barriers due to river stage oscillations: A multiphysics modeling analysis. (*In Preparation*) -->

# Scholarly Presentations

## Invited Talks

**Shuai P.**. (2019). "Hydrologic Exchange Flows and Thermal Regimes in the Hanford Reach: The Effects of Dam Operations, River Morphology and Subsurface Hydrogeology". *Seminar at Washington State University Tri-Cities*, Richland, Washington, United States.

**Shuai P.**. (2019). "Hydrologic Exchange Flows Control on Temperature Regime and Ecological Impacts". *SFA Community Watershed Workshop at PNNL*, Richland, Washington, United States.

**Shuai P.**. (2019). "Simulating flow and heat transport in a large regulated river corridor". *Workshop on Critical Timescales of Hydrologic Transport at University of California, Berkeley*, Berkeley, California, United States.

## Conference Presentations

**Shuai P.**, X. Chen, X. Song, K. Chen, and G. Hammond, (2019). "Dam Induced Hydrologic Exchange Flows Alter River Corridor Thermal Regime." *eLightning presentation at AGU Fall Meeting*, San Francisco, California, United States.

**Shuai P.**, X. Chen, X. Song, K. Chen. (2019). "Boosting Research Reproducibility: Managing High Performance Model Simulation Workflow Using Jupyter Notebook." *Poster presentation at AGU Fall Meeting*, San Francisco, California, United States.

**Shuai P.**, X. Chen, X. Song, K. Chen, and G. Hammond. (2019). "Hydrologic Exchange Flows Alter River Corridor Thermal Regime at Hanford Reach." *Oral presentation at Post-graduate Research Symposium at PNNL*, Richland, Washington, United States.

**Shuai P.**, X. Chen, X. Song, and K. Chen. (2019). "Boosting Research Reproducibility: Managing High Performance Model Simulation Workflow Using Jupyter Notebook." *Oral presentation at Techfest 2019*, Richland, Washington.

**Shuai P.**, X. Chen, X. Song, K. Chen, and G. Hammond. (2019) "Modeling River Corridor Thermal Regime Using High Performance Parallel Subsurface Simulator: An Example with PFLOTRAN." *Oral presentation at Modflow and More 2019*, Golden, Colorado.

**Shuai P.**, X. Chen, X. Song, G. Hammond, J.M. Zachara, P.D. Royer, and H. Ren, et al. (2019). "Dam Operations and Subsurface Hydrogeology Control Dynamics of Hydrologic Exchange Flows in a Large Regulated River Corridor within the Hanford Reach, Washington." *Oral presentation at 12th Washington Hydrogeology Symposium*, Tacoma, Washington.

**Shuai P.**, X. Chen, X. Song, G.E. Hammond, J.M. Zachara, P.D. Royer, and H. Ren, et al. (2018). "Hydrogeomorphic Controls on Hydrologic Exchange Flows Dynamics within a Large Regulated River Corridor." *Poster presentation at AGU Fall meeting*, Washington, DC, United States.

Wang L., **P. Shuai**, P. S. K. Knappett, M. B. Cardenas, (2018) "Accumulation of arsenic in dynamic iron oxide barriers due to river stage oscillations: A multiphysics modeling analysis."" *Oral presentation at AGU Fall meeting*, Washington, DC, United States (presented for Lichun Wang).

**Shuai P.**, X. Chen, X. Song, G.E. Hammond, J.M. Zachara, P.D. Royer, and H. Ren, et al. (2018). "Hydrologic Exchange Flows Dynamics along a Large Regulated River Corridor." *Oral presentation at Post-graduate Research Symposium at PNNL*, Richland, Washington, United States.

**Shuai, P.**, K. Myers, P. S. K. Knappett, M.B. Cardenas (2017) “Tidal and Seasonal River Stage Fluctuations Impact the Formation of Permeable Natural Reactive Barriers in Riverbank Sediments”, *Oral presentation at AGU Fall Meeting*, New Orleans, LA

**Shuai, P.**, A. Hosain, P. S. K. Knappett, S. Hossain, M. B. Cardenas, K. Rhodes, K. M. Ahmed,(2016) “Estimating hydraulic properties of a river bank aquifer under tidal influence”, *Poster presentation at GSA Annual Meeting*, Denver, CO

**Shuai, P.**, Hossain, A., Rhodes, K., Knappett, P. S. K., Dimova, N., Cardenas, M. B., Matin, K. R., Michael, H., Mozumder, R., van Geen, A. (2015) “Modeling arsenic mobilization in a riverbank aquifer under the influence of tidally fluctuating river and irrigation pumping,” *Poster Presentation at AGU Fall Meeting*, San Francisco, CA

# Grants Funded/Research Projects

**Pacific Northwest National Laboratory**, Laboratory Directed Research and Development (Quickstarter), PI \hfill 2019 - 2020

*A collection of Jupyter notebooks for geoscientist*

**U.S. Department of Energy (DOE)**, Subsurface Biogeochemistry Research, Research Associate \hfill 2017 - present

*[Influences of Hydrologic Exchange Flows on River Corridor and Watershed Biogeochemical Function](https://sbrsfa.pnnl.gov/)*

**National Science Foundation (NSF)**, EAR-Hydrologic Sciences, Research Assistant \hfill 2014 - 2017

*[Collaborative Research: The effects of river regulation on lateral and integrated longitudinal mass and energy transfers in coupled terrestrial-aquatic systems](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1344547)*

**Geological Society of America**, Graduate Research Grant, PI \hfill 2015 - 2016

*Investigating impacts of irrigation pumping on Arsenic migration from Meghna River*

**National Program on Key Basic Research Project of China (973 Program)**, Research Assistant \hfill 2011 - 2013

*Evolution Mechanism and Control of Groundwater in the North China Plain*

# Teaching Experience

*Guest Lecturer*, Hydrogeology (GEOL 410), Texas A&M University \hfill 2017

*Graduate Teaching Assistant*, Introduction to Geochemistry (GEOL 453), Texas A&M University \hfill 2017

*Graduate Teaching Assistant*, Hydrogeology (GEOL 410), Texas A&M University \hfill 2016

*Graduate Teaching Assistant*, Physical Geology (GEOL 104), Texas A&M University \hfill 2015

*Graduate Teaching Assistant*, Principals of Geology (GEOL 101), Texas A&M University \hfill 2014

# Fellowships and Awards

*Texas A&M University*, Graduate Fellowship \hfill 2013 - 2017

*Geological Society of America*, On To the Future (OTF) travel award \hfill 2016

<!-- *Geological Society of America*, Student Research Grant \hfill 2015 -->

*Wuhan University (China)*, Graduate Fellowship \hfill 2011 - 2013

# Professional Memberships

American Geophysical Union (AGU), Member \hfill 2015 - present

Geological Society of America (GSA), Member \hfill 2014 - 2015

International Association for Hydro-Environment Engineering and Research (IAHR), Member \hfill 2011-2013

# Professional and Public Service

*Manuscript reviewer* for Water Resources Research (2), Journal of Hydrology (1)

*Student judge* for Outstanding Student Presentation Awards at AGU Anual Meeting 2018

# Skills

<!-- \vspace{-10pt} -->
<!-- \rule{\textwidth}{0.5pt}  -->

\begin{tabular}{@{}ll}
\textit{Programming} & Python, R, Matlab, Shell, SQL, C/C++, Fortran\\
\textit{Numerical model/code} & \href{https://www.pflotran.org/}{PFLOTRAN}, \href{https://github.com/amanzi/ats}{ATS}, \href{https://www.comsol.com/}{COMSOL Multiphysics}, \href{https://water.usgs.gov/ogw/modflow/}{MODFLOW}, \href{https://www.pc-progress.com/en/Default.aspx?hydrus-3d}{HYDRUS 2D}\\
\textit{Other software} & \href{https://www.paraview.org/}{ParaView}, \href{https://www.qgis.org/en/site/}{QGIS}, Adobe Illustrator, Adobe Photoshop, MS Office\\
\textit{Lab/Field} & Ion Chromatography, ADCP, Trimble Total Stations \& RTX, YSI Water Quality Meter,\\
& Solinst Levelogger \& Water Level Meter\\
\textit{OS} & Windows, Unix, Linux\\
\textit{Language} & English, Chinese
\end{tabular}

<!-- ------------------------------------------------------------------------------------ -->
<!-- *Programming*: Matlab••• Python•• R••  Shell•• SQL• C/C++• Fortran• -->

<!-- *Software*: [PFLOTRAN](https://www.pflotran.org/)••• [COMSOL Multiphysics](https://www.comsol.com/)••• [MODFLOW](https://water.usgs.gov/ogw/modflow/)•• [HYDRUS 2D](https://www.pc-progress.com/en/Default.aspx?hydrus-3d)•• [ParaView](https://www.paraview.org/)•• [QGIS](https://www.qgis.org/en/site/)•• Adobe Illustrator••• Adobe Photoshop•• MS Office•••  -->

<!-- *Lab/Field*: Ion Chromatography•• Trimble RTX••  -->

<!-- *OS*: Windows••• Unix•• -->

<!-- *Languages*: Chinese••• English•• -->

<!-- •••Native/Proficient ••Professional/Experienced •Elementary -->

<!-- \makebox[15ex]{Some text} -->

<!-- *Programming*:\quad \cvskill{Matlab}{2}\hfill \cvskill{Python}{2}\hfill \cvskill{R}{2}\par \cvskill{Shell}{2}\hfill \cvskill{SQL}{1}\hfill \cvskill{C/C++}{1} -->

<!-- *Languages*:\quad \cvskill{English}{3}\hfill \cvskill{Chinese}{3} -->

<!-- \begin{tabular}{rl}  -->
<!--     S& Isomeric state\\ -->
<!--     Z& Atomic number\\ -->
<!--     A& Atomic mass number -->
<!-- \end{tabular} -->

<!-- \begin{tabu} to 0.8\textwidth {X[l] X[c] X[c] X[r] } -->
<!--  Programming & \cvskill{English}{3} & \cvskill{Chinese}{3} \\ -->
<!--  item 21  & item 22  & item 23  \\ -->
<!-- \end{tabu} -->

<!-- $\circ$   -->

<!-- \tikz\draw[black,fill=black] (0,0) circle (.3ex); \tikz\draw[black,fill=white] (0,0) circle (.3ex); -->


<!-- *	Proficient with groundwater modeling software such as MODFLOW, HYDRUS, PFLOTRAN and COMSOL Multiphysics (a platform for physics-based modeling and simulation). -->

<!-- *	Proficient in data analysis using MATLAB, R and Python. -->

<!-- *	Familiar with Linux and Unix based operation system and bash commands. -->

<!-- *	Experienced at running codes on massively parallel super computing facilities such as Cori and Edison.   -->

<!-- *	Experienced at 3-D visualization software including ParaView. -->

<!-- *	Experienced at aquifer testing (slug tests and pumping test), monitoring well installation, running and trouble-shooting an Ion Chromatography, advanced GPS equipment including Trimble NetR9’s and R10’s with RTX capability, Total Stations and river discharge measurements using ADCP’s -->
